import Foundation
import SwiftData

/// Static catalog of standard micro-drills the user can carry into their next session.
/// SwiftData-backed so debriefs can reference one canonical record while still supporting
/// custom drills generated by the LLM.
@Model
final class MicroDrill {
    @Attribute(.unique) var id: String
    var title: String
    var body: String
    var category: String

    init(id: String, title: String, body: String, category: String) {
        self.id = id
        self.title = title
        self.body = body
        self.category = category
    }
}

enum MicroDrillCatalog {
    static let seeds: [MicroDrill] = [
        MicroDrill(
            id: "reflect-content",
            title: "Reflect content before reaching for meaning",
            body: "Catch yourself before interpreting. Try one reflection of what they said, in their words, before any reframe.",
            category: "Active listening"
        ),
        MicroDrill(
            id: "name-resistance",
            title: "Name what's in the room",
            body: "When the patient pulls back, gently name it: \"feels like that landed differently than you wanted\". No interpretation — just notice.",
            category: "Rupture repair"
        ),
        MicroDrill(
            id: "sit-with-silence",
            title: "Hold one extra beat of silence",
            body: "After your next reflection, count two breaths before speaking again. Let them choose to fill the space.",
            category: "Pacing"
        ),
        MicroDrill(
            id: "validate-not-agree",
            title: "Validate without agreeing",
            body: "Try \"that makes sense given what you've been carrying\" — acknowledges feeling without endorsing the appraisal.",
            category: "Validation"
        )
    ]
}
